### ISSUE TITLE
cannot add pow or exp function

### ISSUE THREAD

**Issue by Afifa-Tamanna** [ShuhuaGao/geppy#27]
Hi, 
I cannot add power or exponential function in my programme.
if I add 
pset.add_function(operator.pow, 2), the following things return. Could you please help me on this regard?

<string>:1: RuntimeWarning: overflow encountered in double_scalars
Traceback (most recent call last):
  File "G:/My Drive/Afifa Tamanna/PhD/AI/GEP/Diffn_Analysis_GEP_model/Analysis/testviscosity.py", line 180, in <module>
    pop, log = gep.gep_simple(pop, toolbox, n_generations=n_gen, n_elites=1,
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\geppy\algorithms\basic.py", line 100, in gep_simple
    for ind, fit in zip(invalid_individuals, fitnesses):
  File "<__array_function__ internals>", line 5, in lstsq
  File "C:\Users\atam0001\AppData\Roaming\Python\Python38\site-packages\numpy\linalg\linalg.py", line 2259, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "C:\Users\atam0001\AppData\Roaming\Python\Python38\site-packages\numpy\linalg\linalg.py", line 109, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

**Comment by ShuhuaGao** [comment]
Please check #28
