### ISSUE TITLE
after add function of log,  problems occured to visualize

### ISSUE THREAD

**Issue by wenjun820** [ShuhuaGao/geppy#29]
Hello, thank you for sharing these codes.  I have added the function of log in the code, but it failed to visualize as it should be.  is there any method to fix it?

Our symbolic regression process found the following equation offers our best prediction:

         -0.0504234833139171 + 0.24544201652149*(d3 + log(d6))*log(-(11*d1 + 2)*(d2 - d6))/d4

which formally is presented as:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\sympy\core\cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python38\lib\site-packages\pandas\core\generic.py", line 1665, in __hash__
    raise TypeError(
TypeError: 'Series' objects are mutable, thus they cannot be hashed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\sympy\core\cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python38\lib\site-packages\pandas\core\generic.py", line 1665, in __hash__
    raise TypeError(
TypeError: 'Series' objects are mutable, thus they cannot be hashed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GEP-data01.py", line 272, in <module>
    predPE = CalculateBestModelOutput(holdout.d1, holdout.d2, holdout.d3, holdout.d4, holdout.d5, holdout.d6, str(symplified_best))
  File "GEP-data01.py", line 261, in CalculateBestModelOutput
    return eval(model)
  File "<string>", line 1, in <module>
  File "C:\Python38\lib\site-packages\sympy\core\cache.py", line 96, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\sympy\core\function.py", line 465, in __new__
    result = super().__new__(cls, *args, **options)
  File "C:\Python38\lib\site-packages\sympy\core\cache.py", line 96, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\sympy\core\function.py", line 280, in __new__
    evaluated = cls.eval(*args)
  File "C:\Python38\lib\site-packages\sympy\functions\elementary\exponential.py", line 622, in eval
    if arg.is_Number:
  File "C:\Python38\lib\site-packages\pandas\core\generic.py", line 5136, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'is_Number'

**Comment by ShuhuaGao** [comment]
I cannot infer the exact cause from the above information. As we see, the key error is 
>  'Series' objects are mutable, thus they cannot be hashed

Please check whether you have used a `Series` object as a key of a `dict` or something similar.  You may need to debug your program. It seems not related to `geppy`.

**Comment by wenjun820** [comment]
Hello again,
        I think the problem may be due to the function of log.  When I deactive the log function, the code works. 
       I have just made two changes in code basing on the example of UCI power, Firstly, I add a prection version of log like:
      def protected_log(x1):
          if x < 2.718:
                return 2.718
       return log(x)
     pset.add_function(protected_log, 1)

     then, I add the protected_log into the symbolic map function which locates in C:\Python38\Lib\site-packages\geppy\support  -simplication.py
    math.log.__name__: sp.log,
    math.sin.__name__: sp.sin,
    math.cos.__name__: sp.cos,
    math.tan.__name__: sp.tan,
    'protected_log':   sp.log,

     I have tried many times, but the problem still occurs.  I am not familar with python, do you have an example to show how to add  log function?

    Thank you for your attention and response.

**Comment by ShuhuaGao** [comment]
What's your current problem now? It seems what you did is correct.

**Comment by wenjun820** [comment]
Started:         2020-10-12 21:39:45.024993
Ended:           2020-10-12 21:40:43.003110
add(
        protected_log(mul(d5, protected_div(protected_log(d5), mul(protected_div(d5, d2), d6)))),
        mul(protected_log(d5), mul(protected_div(d6, sub(d4, mul(d1, d3))), d6))
)


Our symbolic regression process found the following equation offers our best prediction:

         -0.305123001745898 + 0.134041153830954*(-d6**2*log(d5) + (d1*d3 - d4)*log(d2*log(d5)/d6))/(d1*d3 - d4)

which formally is presented as:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\sympy\core\cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python38\lib\site-packages\pandas\core\generic.py", line 1665, in __hash__
    raise TypeError(
TypeError: 'Series' objects are mutable, thus they cannot be hashed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\sympy\core\cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python38\lib\site-packages\pandas\core\generic.py", line 1665, in __hash__
    raise TypeError(
TypeError: 'Series' objects are mutable, thus they cannot be hashed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GEP-data01.py", line 280, in <module>
    predPE = CalculateBestModelOutput(holdout.d1, holdout.d2, holdout.d3, holdout.d4, holdout.d5, holdout.d6, str(symplified_best))
  File "GEP-data01.py", line 269, in CalculateBestModelOutput
    return eval(model)
  File "<string>", line 1, in <module>
  File "C:\Python38\lib\site-packages\sympy\core\cache.py", line 96, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\sympy\core\function.py", line 465, in __new__
    result = super().__new__(cls, *args, **options)
  File "C:\Python38\lib\site-packages\sympy\core\cache.py", line 96, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\sympy\core\function.py", line 280, in __new__
    evaluated = cls.eval(*args)
  File "C:\Python38\lib\site-packages\sympy\functions\elementary\exponential.py", line 622, in eval
    if arg.is_Number:
  File "C:\Python38\lib\site-packages\pandas\core\generic.py", line 5136, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'is_Number'

**Comment by ShuhuaGao** [comment]
```
TypeError: 'Series' objects are mutable, thus they cannot be hashed
```
It seems that the error is not related to geppy. Note that `sympy` cannot simplify an expression that involves `Series` or other high-level data structures. Generally, it can only handle basic math operations and numbers. 

Besides, if you cannot make it work, you may just remove the simplification.  After all, the symbolic simplification is only a postprocessing step and is not related to GEP. If necessary, you can also try to simplify the final solution manually.
